name: Update gist with WakaTime summary
on:
  schedule:
    - cron: '40 1 * * *' # UTC+0
  workflow_dispatch: # 允许手动触发工作流
  # push:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      # 1.
      - uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # 3. 设置包缓存目录，避免每次下载
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      # 4. 安装依赖
      - name: Install dependencies
        run: npm i --legacy-peer-deps

      # 5. 打包代码
      - name: Build the action
        run: npm run build

      # 6.
      - name: Update gist
        # uses: superman66/wakatime-sync@master
        uses: ./ # 根目录的action.yml
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID}}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # SCU_KEY: ${{ secrets.SCU_KEY }} # 发通知的，不用
  # keepalive-job:
  #   name: Keepalive Workflow
  #   runs-on: ubuntu-latest
  #   permissions:
  #     actions: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: gautamkrishnar/keepalive-workflow@v2
